osteele/liquid

expressions/builders.go, expressions/expressions.go, expressions/expressions_test.go, expressions/filters.go
When a Filter returns an error as its second argument it generates a panic with the error.
I have changed this behaviour so that the error is returned from the RenderAndPass function.
For example, if there is a filter called `toTitle` that returns "test error" as its error, the error returned will be `'Liquid error: error applying filter "toTitle" ("test error") in {{ "test message" | toTitle }}'`.
Apologies if panicing in this case is the expected behaviour and this was done intentionally, I can always just catch the panic when I call the Render step, I just think this way is more elegant.
=> Return errors applying filters as render errors

evaluator/call.go, evaluator/call_test.go
I did this so that I could lift the index function from text/templates which is defined using a variadic function.
=> Support registering variadic functions as filters

engine.go, parser/config.go, parser/parser.go, parser/scanner.go, parser/scanner_test.go
I would like to be able to customise the delimiters I use in templating (this is intended as an analog of https://golang.org/pkg/text/template/#Template.Delims).
This PR has the following problems
1. Delimiters is a byte array to limit them to single ASCII characters
2. The tag delimiters are formed using the objectLeft and objectRight argument, I would like to specify all 4 combinations completely, e.g., "<<", ">>", "<%", "%>".
3. I think moving compilation of the `tokenMatcher` regex into the function call will dramatically slow things down.
4. There are no tests.
I did it like this so I didn't have to change the existing code much.
I am happy to continue work on this, but I'm lodging a PR to see if you're willing to accept this sort of functionality, if I'm going about implementing in …
=> Add setting to customise delimiters

values/call.go, values/call_test.go
This commit addresses two issues:
1. For variadic functions 'convertCallArguments' was allocating exactly
'len(args)' arguments, which might be less than required, as a result
zero/default filling loop would panic with out of bounds error.
2. Even if we correctly allocate a proper amount of arguments, zero/default
filling loop doesn't handle special variadic function type case, when last
argument has a slice type and reflect API expects plain values as arguments.
But actually we don't need that, because it's okay to omit variadic values
altogether, hence the total amount of allocated arguments is
max(len(args), rt.NumIn()-1).
=> Properly handle variadic functions.

filters/standard_filters.go, filters/standard_filters_test.go
See
- https://shopify.github.io/liquid/filters/floor/
- https://shopify.github.io/liquid/filters/ceil/
=> floor and ceil should return integers

expressions/y.go
This fixes an issue where math.MaxUint32 is assigned to a platform
dependent int type. This works on 64-bit platforms without issue due to
there being plenty of space. On 32-bit platforms this is wrong and will
not compile as math.MaxUint32 > math.MaxInt32.
=> 🐛 Fix MaxUint32 assignment to platform int

engine.go, engine_test.go, render/config.go, render/context.go, tags/include_tag_test.go
Hi there!
I'm a bit uncomfortable about opening this PR since this behaviour is not part of Shopify's API. So please feel free to disregard this.
I found myself using this package with a "virtualised" file system, in which templates are embedded into my binary, rather than being available in directories. This adds a new `ParseTemplateAndCache` method to `Engine` that caches a provided template, and allows `{% include %}` tags to use them, in case the file is not present in disk.
=> Add support to cached templates

template.go, template_test.go
Sometimes a consumer of a template needs to know what objects were used. In my case, a template can reference secret values from a secret store vault and instead of passing all possible secrets to the template only to render two of them, we use the ast to determine which are used and only retrieve those values from the vault before rendering the template.
Exposing the ast allows us to use the liquid APIs just like normal, without having to jump through hoops to build the ast ourselves using the other types exported in this library.
=> Expose the template ast

README.md, cmd/liquid/main.go, cmd/liquid/main_test.go, engine.go, render/config.go, render/render.go, render/render_test.go
The Ruby implementation has support for erroring when a template has an undefined variable. This is implemented by passing an option to the render() method.
As this version doesn't expose render.Config in the engine, a StrictVariables() method is provided on the engine to enable it. This differs from the Ruby version in that it's on for the entire engine, rather than enabled for each call to Render(). This is more similar to the Ruby version's render!() method as it immediately errors, rather than storing a stack of errors which can be accessed later.
Refs. #8
=> Add support for strict variables

expressions/expressions.y, expressions/expressions_test.go, expressions/statements.go, expressions/statements_test.go, expressions/y.go, tags/iteration_tags.go, tags/iteration_tags_test.go
This PR adds the ability to specify variables and expressions in loop modifiers. Example:
```liquid
{% assign limit = 3 %}
{% assign offset = 1 %}
{% for i in (1..5) limit:limit offset:offset %}
{{ i -}}
{%- endfor %}
```
results in:
```
2
3
4
```
=> Allow loop modifiers to be more than just literals

tags/control_flow_tags_test.go, tags/standard_tags.go
This PR adds the [`else`](https://shopify.github.io/liquid/tags/control-flow/#elsif--else) clause to `unless`
=> Allow unless to have an else clause

filters/standard_filters.go, filters/standard_filters_test.go
The previous map implementation worked only for slices of maps. By using the library's `values` package this implementation should work with all compatible types.
=> Fix map filter with slice of structs

render/context.go
I like to implement a tag, that require the full lexical context (bindings) to be copied. Currently the `render.Context` interface exposes the `Get` and `Set` function to manipulate the bindings, but those don't let me iterate over the whole thing. Thus, this PR adds a function that returns the full bindings. Usage example:
```go
func (tc tagContext) myTag(rc render.Context) (s string, err error) {
bindings := rc.Bindings()
...
}
```
=> Expose the template lexical environment

tags/iteration_tags_test.go, tags/standard_tags_test.go, values/convert.go, values/convert_test.go, values/range.go
Currently the range expression `(start..end)` is only supported in loops. This PR makes is possible to use it as a general expression e.g.:
```liquid
{% assign l = (1..5) | reverse %}
{% for i in l %}
{{ i -}}
{% endfor %}
```
results in:
```
5
4
3
2
1
```
=> Allow range expression as general expressions (not only loops)

engine.go, engine_test.go, template.go
=> Add FRender to allow rendering into a custom io.Writer

.github/workflows/go.yml, .github/workflows/golangci-lint.yml, CHANGELOG.md
This PR bumps GitHub workflow actions to latest versions, thus avoiding deprecation warnings as seen e.g. [here](https://github.com/osteele/liquid/actions/runs/8846283387).
=> Bump GitHub workflow actions to latest versions

tags/iteration_tags.go, tags/iteration_tags_test.go, tags/standard_tags.go
What it says on the tin!
I added a handful of basic tests, but I'm happy to add more if there are any cases I've missed.
=> implement support for else clauses in for loops. fixes osteele/liquid#46

parser/parser.go
=> patch: add nil check for grammer field before g.BlockSyntax call

parser/ast.go, parser/parser.go, parser/scanner.go, parser/scanner_test.go, parser/token.go, render/compiler.go, render/nodes.go, render/render.go, render/render_test.go, render/trimwriter.go
Instead of keeping trimming flags on all tokens, introduce explicit trim tokens: `TrimLeftTokenType` and `TrimRightTokenType`, `trimWriter` configuration is then triggere via `(n *TrimNode) render`.
=> Fix whitespace control

filters/standard_filters.go, filters/standard_filters_test.go
=> Don't panic in filter divided_by on division by zero

filters/standard_filters_test.go, values/arrays.go
=> Count number of characters in size filter instead of number of bytes

engine.go, engine_test.go
This PR follows up [this issue](https://github.com/osteele/liquid/issues/102) I raised recently.
I'd like to add new function to create a "basic" liquid engine which provides an instance of the liquid engine without the standard filters or tags registered. This would allow the developer to still render variables in a liquid template, but only use tags and filter they wish to register.
=> Add a NewBasicEngine function

README.md, docs/TemplateStoreExample.md, engine.go, engine_test.go, render/config.go, render/context.go, render/file_template_store.go, values/drop_test.go
Implement template loader.
- Implements a template loader as described here [issue 38](https://github.com/osteele/liquid/issues/38)
- Unit Tests Added
- Documentation updates
=> Implement template loader

engine.go, expressions/filters.go, render/autoescape.go, render/autoescape_test.go, render/config.go, render/render.go, values/value.go
=> Implemented auto-escape functionality and provided a default escape replacer for HTML.
